JamesDjango/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from JamesDjango.settings import MEDIA_ROOT
from django.views.static import serve
from django.views.static import serve
from . import settings
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('task/', include('Task.urls')),
    path('upload/', include('upload.urls')),
    path('wiki/', include('wiki.urls')),
    path('monitor/', include('monitor.urls')),
    path('jumpserver/', include('jumpserver.urls')),
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    path('', include('mysites.urls')),
]

Task/urls.py
from django.urls import path
from django.conf.urls import include, url
from Task import views

urlpatterns = [
    url('tasklist', views.tasklist, name='tasklist'),
    url('taskinfo', views.taskinfo, name='taskinfo'),
    url('addtask', views.addtask, name='addtask'),
    url('edittask', views.edittask, name='edittask'),
    url('deltask', views.deltask, name='deltask'),
    url('starttask', views.starttask, name='starttask'),
    url('complatetask', views.complatetask, name='complatetask'),
    url('add_task_point', views.add_task_point, name='add_task_point'),
    url('del_task_point', views.del_task_point, name='del_task_point'),
    url('done_task_point', views.done_task_point, name='done_task_point'),
    url('edit_task_point', views.edit_task_point, name='edit_task_point'),
]

Task/models.py
from django.db import models

# Create your models here.

class tasks(models.Model):
    '''任务表'''
    GENDER_CHOICES = (
        (0, '不急加重'),
        (1, '不急'),
        (2, '正常'),
        (3, '紧急'),
        (4, '加急'),
        (5, '重要'),
        (6, '加重'),
        (7, '不急重要'),
    )
    GENDER_CHOICES1 = (
        (0, '未启动'),
        (1, '进行中'),
        (2, '完成'),
    )

    id = models.AutoField(primary_key=True)
    tasktype = models.SmallIntegerField(choices=GENDER_CHOICES, default=1, verbose_name='任务类型')
    title = models.CharField(max_length=128,null=False)
    description = models.FileField(null=True)
    tags = models.CharField(max_length=200,null=True)
    """创建时间""" 
    c_time = models.DateTimeField(null=False)
    """开始时间""" 
    s_time = models.DateTimeField(null=True)
    """完成时间""" 
    f_time = models.DateTimeField(null=True)
    username = models.ForeignKey('Users.UserInfo',to_field='username',null=True,on_delete=models.CASCADE)
    doc = models.ForeignKey('wiki.doc',to_field='id',null=True,on_delete=models.CASCADE)
    status = models.SmallIntegerField(choices=GENDER_CHOICES1, default=0, verbose_name='任务状态')


    class Meta:
        db_table = 'tasks'
        ordering = ['c_time']

class task_point(models.Model):
    """记录一个大任务分开成几个小任务去完成"""
    GENDER_CHOICES = (
        (0, '未启动'),
        (1, '进行中'),
        (2, '完成'),
    )
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=128,null=False)
    c_time = models.DateTimeField(null=True)
    f_time = models.DateTimeField(null=True)
    status = models.SmallIntegerField(choices=GENDER_CHOICES, default=1, verbose_name='小任务状态') 
    task = models.ForeignKey('Task.tasks',to_field='id',null=True,on_delete=models.CASCADE)
    class Meta:
        db_table = 'task_point'
        ordering = ['c_time']

Task/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from datetime import *
from Users.initTime import initTime
from Task.models import tasks
from Task.models import task_point
from upload.models import IMG
from Task.makeTaskid import taskidMD5,tag_tagcolor
from Task.choices_switch import choices_switch
from Users.views import login_require
from Users.models import UserInfo
import json,os 
from JamesDjango.settings import MEDIA_ROOT
from django.core.paginator import Paginator , PageNotAnInteger,EmptyPage
# Create your views here.


    
@login_require
def tasklist(request):
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskinfolist = tasks.objects.all()
    input_title = request.POST.get('title') 
    input_username = request.POST.get('username') 
    input_status = request.POST.get('status') 
    input_search_field = "title"
    input_keyword = ""
    if request.method == "POST":
        input_search_field = request.POST.get("search_field")
        input_keyword = request.POST.get("keyword",None)
        """标题检索"""
        if input_search_field == "title":
            taskinfolist = tasks.objects.all().filter(title__icontains=input_keyword)
        """作者检索"""
        if input_search_field == "username":
            taskinfolist = tasks.objects.all().filter(username=input_keyword)
        """状态检索"""
        if input_search_field == "status":
            status_code = choices_switch("GENDER_CHOICES1",input_keyword)
            taskinfolist = tasks.objects.all().filter(status=status_code )  
        """类型检索"""
        if input_search_field == "tasktype":
            tasktype_code = choices_switch("GENDER_CHOICES",input_keyword)
            taskinfolist = tasks.objects.all().filter(tasktype=tasktype_code)

    tasklist_json = tag_tagcolor(taskinfolist)

    """"分页"""
    # 值1：所有的数据
    # 值2：每一页的数据
    # 值3：当最后一页数据少于n条，将数据并入上一页
    paginator = Paginator(tasklist_json,10,3)
    try:
        # GET请求方式，get()获取指定Key值所对应的value值
        # 获取index的值，如果没有，则设置使用默认值1
        num = request.GET.get('index','1')
        # 获取第几页
        number = paginator.page(num)
    except PageNotAnInteger:
        # 如果输入的页码数不是整数，那么显示第一页数据
        number = paginator.page(1)
    except EmptyPage:
        number = paginator.page(paginator.num_pages)

    context = {"userinfo":userinfo[0],"tasklist_json":tasklist_json,"input_search_field":input_search_field,"input_keyword":input_keyword, 'page':number,'paginator':paginator}
    return render(request,'task/tasklist.html',context)


@login_require
def taskinfo(request):
    username = request.session.get("username",None)
    userinfo = UserInfo.objects.filter(username=username)
    input_task_id = request.GET.get("task_id",None)
    taskinfo = tasks.objects.all().filter(id=input_task_id)
    task_point_list = task_point.objects.filter(task_id=input_task_id)
    imglist = IMG.objects.all().filter(task_id=input_task_id)
    taglist = taskinfo[0].tags.split(",")
    taskinfo = tag_tagcolor(taskinfo)
    # context={"username":username,"taskinfo":taskinfo[0],"task_point_list":task_point_list,"imglist":imglist,"task_id":input_task_id,"taglist":taglist}
    context={"userinfo":userinfo[0],"taskinfo":taskinfo[0],"task_point_list":task_point_list,"imglist":imglist}
    return render(request,'task/taskinfo.html',context)



@login_require
def addtask(request):
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskid = taskidMD5(username)
    request.session['taskidMD5'] = taskid
    imgs=IMG.objects.all()
    context = {"userinfo":userinfo[0],"imgs":imgs}
    print("*____________________"* 3)
    if request.method == "POST":
        """输入"""
        input_tasktype = request.POST.get("type",None)
        input_title = request.POST.get("title",None)
        input_description = request.POST.get("description",None)
        input_tags = request.POST.get("tags",None)
        input_status = request.POST.get("status",None)
        """需要添加"""
        input_ctime = initTime() 
        new_task = tasks(
            username_id=username,
            title = input_title,
            tasktype = input_tasktype,
            tags = input_tags,
            c_time = input_ctime,
            status = input_status, 
            description = input_description,
        ) 
        new_task.save()
        # print("新任务的ID号："+ str(new_task.id))
        IMG.objects.filter(active=taskid).update(task_id=new_task.id,active=None)         
        # print(input_tasktype,input_title,input_description,input_tags,input_status)
        return HttpResponseRedirect('task/tasklist.html',context)
    return render(request,'task/addtask.html',context)

@login_require
def edittask(request):
    input_task_id = request.GET.get("task_id",None)
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskid = taskidMD5(username)
    request.session['taskidMD5'] = taskid
    taskinfo = tasks.objects.all().filter(id=input_task_id)
    imglist = IMG.objects.all().filter(task_id=input_task_id)
    context = {"userinfo":userinfo[0],"taskinfo":taskinfo[0],"imglist":imglist,"task_id":input_task_id}
    if input_task_id != None:
        if request.method == "POST":
            taskinfolist = tasks.objects.all()
            context = {"userinfo":userinfo[0],"taskinfolist":taskinfolist}
            input_tasktype = request.POST.get("type",None)
            input_title = request.POST.get("title",None)
            input_description = request.POST.get("description",None)
            input_tags = request.POST.get("tags",None)
            input_status = request.POST.get("status",None)
            input_task_id = request.GET.get("task_id",None)
            if input_task_id != None:
                taskinfo.update(title=input_title,tasktype=input_tasktype,tags=input_tags,status=input_status,description=input_description)
                IMG.objects.filter(active=taskid).update(task_id=input_task_id,active=None)  
            return HttpResponseRedirect('/task/tasklist.html',context)
        return render(request,'task/edittask.html',context )
    else:
        return HttpResponse("没有如此ID")
        
@login_require
def deltask(request):
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskinfolist = tasks.objects.all()
    """获取复选框内容"""
    check_box_list = request.GET.getlist('ids[]')
    """获取id对象"""
    for input_task_id in check_box_list:
        """获取id的对象"""
        taskinfo = tasks.objects.filter(id=input_task_id)
        """删除任务图片"""
        img = IMG.objects.all().filter(task_id=input_task_id)
        if len(img) > 0:
            os.remove(MEDIA_ROOT+ "/img/" + img[0].name)
        """移除task"""
        taskinfo.delete()

        

    context = {"userinfo":userinfo[0],"taskinfolist":taskinfolist}
    return HttpResponseRedirect('/task/tasklist.html',context)
@login_require
def starttask(request):
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskinfolist = tasks.objects.all()
    """获取复选框值"""
    check_box_list = request.GET.getlist('ids[]')
    """点击启动，如何启动时间为None则修改启动时间，修改task状态"""
    for input_task_id in check_box_list:
        """获取id的对象"""
        taskinfo = tasks.objects.filter(id=input_task_id)
        """只有状态是未启动【0】的时候才会启动"""
        if taskinfo[0].status == 0:
            taskinfo.update(status=1)
        """修改启动时间"""
        if taskinfo[0].s_time == None:
            input_stime = initTime() 
            taskinfo.update(s_time=input_stime)
    context = {"userinfo":userinfo[0],"taskinfolist":taskinfolist}
    return HttpResponseRedirect('/task/tasklist.html',context)
@login_require
def complatetask(request):
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    taskinfolist = tasks.objects.all()
    context = {"userinfo":userinfo[0],"taskinfolist":taskinfolist}
    """获取复选框值"""
    check_box_list = request.GET.getlist('ids[]')
    """获取taskid对象"""
    for input_task_id in check_box_list:
        """获取对象"""
        taskinfo = tasks.objects.filter(id=input_task_id)
        """只有状态为进行中的时候才可以修改状态"""
        """修改完成时间"""
        if taskinfo[0].status == 1:
            input_ftime = initTime() 
            taskinfo.update(status=2,f_time=input_ftime)
    return HttpResponseRedirect('/task/tasklist.html',context)
@login_require
def add_task_point(request):
    input_task_id = request.GET.get("task_id",None)
    username = request.session.get("username", None)
    userinfo = UserInfo.objects.filter(username=username)
    task_point_info = task_point.objects.all().filter(task_id=input_task_id)
    context = {"userinfo":userinfo[0],"task_point_info":task_point_info,"task_id":input_task_id}
    if input_task_id != None:
        context = {"userinfo":userinfo[0],"task_point_info":task_point_info,"task_id":input_task_id}
        if request.method == "POST":
            input_ctime = initTime()
            input_status = request.POST.get("type",None)
            input_title = request.POST.get("title",None) 
            if input_title != None:
                if input_status != 2:
                    new_task_point = task_point(
                        title = input_title,
                        c_time = input_ctime,
                        f_time = input_ctime,
                        status = input_status,
                        task_id = input_task_id
                    )
                    new_task_point.save() 
                else:
                    new_task_point = task_point(
                        title = input_title,
                        c_time = input_ctime,
                        status = input_status,
                        task_id = input_task_id
                    )
                    new_task_point.save()
              
    else:

templates/task/add_task_point.html
{% extends "bases/sidebar.html" %}
{% block content %}










    <!--页面主要内容-->
    <main class="lyear-layout-content">

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
 





<ul class="nav nav-tabs page-tabs">
  <li> <a href="/task/tasklist">任务列表</a> </li>
  <li> <a href="/task/addtask/">添加大任务</a> </li>
  <li> <a href="/task/edittask/?task_id={{ task_id }}">修改任务</a> </li>
  <li class="active"> <a href="#!">添加小任务</a> </li>
  <li> <a href="/task/taskinfo/?task_id={{ task_id }}">任务详情</a> </li>
  <li> <a  onclick="javascript:history.back(-1);return false;">返回</a> </li>
</ul>

               

                <form action="#!" method="post" class="row">
                    {% csrf_token %}
                  <div class="form-group col-md-12">
                    <label for="type">任务状态</label>
                    <div class="form-controls">
                      <select name="type" class="form-control" id="type">
                        <option value="0">未启动</option>
                        <option value="1">进行中</option>
                        <option value="2">完成</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="" placeholder="请输入标题" />
                  </div>
                  <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-primary ajax-post" target-form="add-form">确 定</button>
                    <button type="button" class="btn btn-default" onclick="javascript:history.back(-1);return false;">返 回</button>
                  </div>
                </form>

                <div class="table-responsive">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>标题</th>
                        <th>创建时间</th>
                        <th>完成时间</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for task_point in task_point_info %}
                      <tr>
                        <td>{{ task_point.title}}</td>
                        <td>{{ task_point.c_time}}</td>
                        <td>{{ task_point.f_time}}</td>
                        <td><font class="text-success">{{ task_point.get_status_display }}</font></td>
                        <td>
                          <div class="btn-group">
                            <a class="btn btn-xs btn-default" href="/task/edit_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="编辑"><i class="mdi mdi-pencil"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/done_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="完成"><i class="mdi mdi-library"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/del_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="删除"><i class="mdi mdi-window-close"></i></a>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
          </div>
        </div>
      </div>
      
    </div>
    
  </div>
  
</main>
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="/static/js/main.min.js"></script>
</body>
</html>
{% endblock content %}

templates/task/edit_task_point.html
{% extends "bases/sidebar.html" %}
{% block content %}










    <!--页面主要内容-->
    <main class="lyear-layout-content">

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
 





            <ul class="nav nav-tabs page-tabs">
                <li> <a href="/task/tasklist">任务列表</a> </li>
                <li> <a href="/task/addtask/">添加大任务</a> </li>
                <li> <a href="/task/edittask/">修改任务</a> </li>
                <li class="active"> <a href="#!">添加小任务</a> </li>
                <li> <a href="/task/taskinfo/?task_id={{ task_id }}">任务详情</a> </li>
                <li> <a  onclick="javascript:history.back(-1);return false;">返回</a> </li>
              </ul>

               

                <form action="#!" method="post" class="row">
                    {% csrf_token %}
                  <div class="form-group col-md-12">
                    <label for="type">任务状态</label>
                    <div class="form-controls">
                      <select name="type" class="form-control" id="type">
                        <option value="0">未启动</option>
                        <option value="1">进行中</option>
                        <option value="2">完成</option>
                        <option selected="selected" value="{{ task_point1.status }}">{{ task_point1.get_status_display}}</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{task_point1.title}}" placeholder="请输入标题" />
                  </div>

                  <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-primary ajax-post" target-form="add-form">确 定</button>
                    <button type="button" class="btn btn-default" onclick="javascript:history.back(-1);return false;">返 回</button>
                  </div>
                </form>

                <div class="table-responsive">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>标题</th>
                        <th>创建时间</th>
                        <th>完成时间</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for task_point in task_point_info %}
                      <tr>
                        <td>{{ task_point.title}}</td>
                        <td>{{ task_point.c_time}}</td>
                        <td>{{ task_point.f_time}}</td>
                        <td><font class="text-success">{{ task_point.get_status_display }}</font></td>
                        <td>
                          <div class="btn-group">
                            <a class="btn btn-xs btn-default" href="/task/edit_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="编辑"><i class="mdi mdi-pencil"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/done_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="完成"><i class="mdi mdi-library"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/del_task_point?task_id={{ task_id}}&task_point_id={{ task_point.id }}" title="" data-toggle="tooltip" data-original-title="删除"><i class="mdi mdi-window-close"></i></a>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
          </div>
        </div>
      </div>
      
    </div>
    
  </div>
  
</main>
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="/static/js/main.min.js"></script>
<!--时间选择插件-->
<script src="/static/js/bootstrap-datetimepicker/moment.min.js"></script>
<script src="/static/js/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
<script src="/static/js/bootstrap-datetimepicker/locale/zh-cn.js"></script>
<!--日期选择插件-->
<script src="/static/js/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/static/js/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
<script type="text/javascript" src="/static/js/main.min.js"></script>
</body>
</html>
{% endblock content %}

templates/task/tasklist.html
{% extends "bases/sidebar.html" %}
{% block content %} 
    <!--页面主要内容-->
    <main class="lyear-layout-content">
      
      <div class="container-fluid">
        
        <div class="row">
          <div class="col-lg-12">
            <div class="card">

         <ul class="nav nav-tabs page-tabs">
           <li class="active"> <a href="/task/tasklist">任务列表</a> </li>
           <li> <a href="/task/addtask">添加任务</a> </li>
           <li> <a  onclick="javascript:history.back(-1);return false;">返回</a> </li>
         </ul>       
              <div class="card-toolbar clearfix">
                <form class="pull-right search-bar" method="POST" action="" role="form">
                   {% csrf_token %}
                  <div class="input-group">
                    <div class="input-group-btn">
                      <input type="hidden" name="search_field" id="search-field" value="title">
                      <button class="btn btn-default dropdown-toggle" id="search-btn" data-toggle="dropdown" type="button" aria-haspopup="true" aria-expanded="false">
                          标题 <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu">
                        <li> <a tabindex="-1" href="javascript:void(0)" data-field="title">标题</a> </li>
                        <li> <a tabindex="-1" href="javascript:void(0)" data-field="username">作者</a> </li>
                        <li> <a tabindex="-1" href="javascript:void(0)" data-field="status">状态</a> </li>
                        <li> <a tabindex="-1" href="javascript:void(0)" data-field="tasktype">类型</a> </li>
                      </ul>
                    </div>
                    <input type="text" class="form-control" value="{{ input_keyword }}" name="keyword" placeholder="请输入需要检索的内容">
                  </div>
                </form>
                <form name="form1">   
                <div class="toolbar-btn-action">
                  <a class="btn btn-primary m-r-5" href="/task/addtask"><i class="mdi mdi-plus"></i> 新增</a>
                  <button type="submit" class="btn btn-success m-r-5 mdi mdi-check"   onclick="starttask();" >启用</button>
                  <button type="submit" class="btn btn-warning m-r-5 mdi mdi-block-helper"   onclick="complatetask();" >完成</button>
                  <button type="submit" class="btn btn-info m-r-5 mdi mdi-window-close" onclick="deltask();">移除</button>
                </div>
              </div>
              <div class="card-body"> 
                <div class="table-responsive">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>
                          <label class="lyear-checkbox checkbox-primary">
                            <input type="checkbox" id="check-all"><span></span>
                          </label>
                        </th>
                        <th>标题</th>
                        <th>标签</th>
                        <th>作者</th>
                        <th>创建时间</th>
                        <th>启动时间</th>
                        <th>结束时间</th>
                        <th>状态</th>
                        <th>类型</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for taskinfo in page.object_list %}
                      <tr>
                        <td>
                          <label class="lyear-checkbox checkbox-primary">
                            <input type="checkbox" name="ids[]" value="{{ taskinfo.id }}"><span></span>
                          </label>
                        </td>
                        <td>{{ taskinfo.title  }}</td>
                        <td>
                          {% for tag in taskinfo.tags  %}
                        <span class="label {{ tag |last}}">{{ tag |first  }}</span>
                         {% endfor %}
                        </td>
                        <td>{{ taskinfo.username }}</td>
                        <td>{{ taskinfo.c_time }}</td>
                        <td>{{ taskinfo.s_time }}</td>
                        <td>{{ taskinfo.f_time }}</td>
                        <!-- <td><font class="text-warning">{{ taskinfo.get_status_display }}</font></td>
                        <td><font class="text-success">{{ taskinfo.get_tasktype_display }}</font></td> -->
                        <td><font class="text-warning">{{ taskinfo.status}}</font></td>
                        <td><font class="text-success">{{ taskinfo.tasktype }}</font></td>
                        <td>
                          <div class="btn-group">
                            <a class="btn btn-xs btn-default" href="/task/edittask?task_id={{ taskinfo.id }}" title="编辑" data-toggle="tooltip"><i class="mdi mdi-pencil"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/add_task_point?task_id={{ taskinfo.id }}" title="创建小任务" data-toggle="tooltip"><i class="mdi mdi-format-list-bulleted"></i></a>
                            <a class="btn btn-xs btn-default" href="/task/taskinfo?task_id={{ taskinfo.id }}" title="任务详情" data-toggle="tooltip"><i class="mdi mdi-content-paste"></i></a>
                            <a class="btn btn-xs btn-default" href="/wiki/Solve_doc?task_id={{ taskinfo.id }}" title="解决文档" data-toggle="tooltip"><i class="mdi mdi-book-open-page-variant"></i></a>
                          </div>
                        </td>
                        {% endfor %}
                      </tr>
                    </tbody>
                  </table>
                </div>
              </form>

                <ul class="pagination">
                  {# 如果当前页还有上一页 #}
                  {% if page.has_previous %}
                      <li>
                          {# 点击a标签，跳转到上一页链接 ?index  为地址后面拼接的参数 #}
                          <a href="?index={{page.previous_page_number}}">上一页</a>
                      </li>
                  {% else %}
                      {# 如果没有上一页， 则上一页按钮不可点击 #}
                      <li class="disabled">
                          <a href="#">上一页</a>
                      </li>
                  {% endif %}
                  {% for page_number in paginator.page_range %}
                  {# 获取当前页的页码 #}
            {% if page_number == page.number %}
                {# 如果是当前页的话，选中 #}
                <li class="active">
                    <a href="?index={{page_number}}">{{page_number}}</a>
                </li>
            {% else %}
                <li>
                    <a href="?index={{page_number}}">{{page_number}}</a>
                </li>
            {% endif %}
        {% endfor %}
 
        {% if page.has_next %}
            <li>
                <a href="?index={{page.next_page_number}}">下一页</a>
            </li>
        {% else %}
        <li class="disabled">
            <a href="#">下一页</a>
        </li>
        {% endif %}
      
              </div>
            </div>
          </div>
          
        </div>
        
      </div>
      
    </main>
    <!--End 页面主要内容-->
  </div>
</div>

<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="/static/js/main.min.js"></script>
<script type="text/javascript">
$(function(){
    $('.search-bar .dropdown-menu a').click(function() {
        var field = $(this).data('field') || '';
        $('#search-field').val(field);
        $('#search-btn').html($(this).text() + ' <span class="caret"></span>');
    });
});
</script>
<script> 
    function starttask(){ 
    document.form1.action="/task/starttask"; 
    document.form1.submit(); 
    } 
    function complatetask(){ 
    document.form1.action="/task/complatetask"; 
    document.form1.submit(); 
    } 
    function deltask(){ 
    document.form1.action="/task/deltask"; 
    document.form1.submit(); 
    } 
    </script>
</body>
</html>
{% endblock content %}